api:
  version: 1.0.0
  title: ITO-TEST API
  basePackage: com.jcgfdev.itoTest
  description: Automated JSON API documentation for API's build with Spring
  terms: https://

server:
  servlet:
    context-path: /ito-test-api
  port: ${PORT:8080}
  error:
    include-message: always
    include-binding-errors: always
# swagger-ui custom path
springdoc:
  api-docs:
    path: /api-docs

spring:
  jpa:
    hibernate.ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL5Dialect
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/itotest
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
